version: '3.8' # Specify the version of the compose file
services:
  app:
    image: demo-app
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DB_NAME: db
      AWS_REGION: eu-north-1
      REDIS_HOST: redis       # Redis hostname for the app to connect
      REDIS_PORT: 6379
      SPRING_REDIS_PORT: 6379        # Redis port
      SPRING_REDIS_HOST: redis
    volumes:
      - ./:/src
    command: >
      /bin/sh -c "./wait-for-it.sh db:3306 -- java -jar build/libs/demo-0.0.1-SNAPSHOT.jar"
  
  

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"

volumes:
  db-data:
    driver: local
